FROM python:3.10-slim
WORKDIR /app
RUN pip install --no-cache-dir \
    torch==2.1.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir \
    torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir flask pillow
COPY infer.py .
EXPOSE 8080
CMD ["python", "infer.py"]
