apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: mnist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 5Gi
